# Generated by Django 5.2 on 2026-04-17 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=500)),
                ('product_category', models.CharField(blank=True, max_length=200)),
                ('query_type', models.CharField(choices=[('buy', 'Buy'), ('learn', 'Learn'), ('others', 'Others')], max_length=20)),
                ('image_url', models.URLField(blank=True, max_length=800)),
                ('tokens_used', models.IntegerField(default=2)),
                ('was_free', models.BooleanField(default=False)),
                ('result_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search History',
                'verbose_name_plural': 'Search History',
                'ordering': ['-created_at'],
            },
        ),
    ]
