# Generated by Django 5.2 on 2026-04-12 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('order_reference', models.CharField(blank=True, max_length=200)),
                ('product_name', models.CharField(max_length=300)),
                ('product_image', models.URLField(blank=True, max_length=800)),
                ('supplier_name', models.CharField(max_length=200)),
                ('supplier_platform', models.CharField(blank=True, max_length=50)),
                ('carrier', models.CharField(blank=True, max_length=100)),
                ('carrier_tracking_url', models.URLField(blank=True, max_length=800)),
                ('origin_country', models.CharField(blank=True, max_length=100)),
                ('destination_address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('order_placed', 'Order Placed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('exception', 'Exception / Held'), ('returned', 'Returned')], default='order_placed', max_length=30)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('is_visible_to_user', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shipment Tracking',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracking.shipmenttracking')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
