# Generated by Django 5.2 on 2026-04-17 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens_per_pack', models.IntegerField(default=2)),
                ('price_naira', models.DecimalField(decimal_places=2, default=200.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('label', models.CharField(default='Standard Pack', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token Pricing',
                'verbose_name_plural': 'Token Pricing',
            },
        ),
        migrations.CreateModel(
            name='UserTokenBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens', models.IntegerField(default=0)),
                ('is_first_search', models.BooleanField(default=True)),
                ('total_searches', models.IntegerField(default=0)),
                ('total_tokens_bought', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token_balance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
