# Generated by Django 5.2 on 2026-04-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geminiSearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geminisearchhistory',
            name='ai_provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('anthropic', 'Anthropic Claude'), ('vision', 'Google Cloud Vision + Gemini')], default='gemini', max_length=20),
        ),
    ]
